name: CI/CD for Node.js App

on:
  push:
    branches: [ main ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Run Tests
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # Step 3: Build and Push Docker Image
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

    # Step 4: Deploy to EC2
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          sudo docker stop my-node-app || true
          sudo docker rm my-node-app || true
          sudo docker run -d --name my-node-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
